title: My github-pages website
author: mcwen
email: xxx
description: > # this means to ignore newlines until "baseurl:"
  Miłosz Cwen webdeveloper

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  miloszcwen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

